src/objects/Break_Fix__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>This is a Break Fix Knowledge article type.</description>
    <fields>
        <fullName>Product__c</fullName>
        <inlineHelpText>Describe which product(s) the article addresses.</inlineHelpText>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <inlineHelpText>Please describe the resolution of the problem.</inlineHelpText>
        <label>Resolution</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Symptom__c</fullName>
        <inlineHelpText>Include a description of the symptoms or problem statement. If applicable, copy and paste the error message.</inlineHelpText>
        <label>Symptom</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <label>Break Fix</label>
    <pluralLabel>Break Fixes</pluralLabel>
</CustomObject>

src/objects/DataValueMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This cs is used to hold all the data value required to customize functionality</description>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Data Value Map</label>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire XD</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GPText</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Greenplum</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Greenplum Command Center</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/classes/PS_FeedItemComment_Test.cls
@isTest
public class PS_FeedItemComment_Test {
 	static testMethod void  FeedItemCommentTriggerHandlerTest(){
       TestDataUtil.dataValueMapCSData();
       Case cObj = TestDataUtil.createTechnicalCase();
       system.assert(cObj.Id != null);
       FeedItem feed = TestDataUtil.createFeedItem(cObj.Id,'AllUsers');
       system.assert(feed.Id != null);
	   Test.startTest();
           Contact cont = TestDataUtil.createPortalContact();
           system.assert(cont != null);
           User usr = [Select Id , ContactId , AccountId from User where isActive = true and Profile.Name='Pivotal - Community Manager' limit 1];
           system.assert(usr != null,'Issue in creating User');
           Case cObj1;
            System.runAs(usr){
               cObj1 = TestDataUtil.createCaseByPortalUser(usr);
               System.assert(cObj1.Id != null,'Case not created');
            }
           cObj1.Status = 'Solved';
           update cObj1;
       Test.stopTest();

       System.runAs(usr){
           FeedItem ifeed = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           FeedItem ifeed2 = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           system.assert(ifeed.Id != null);
       }
    }
    
    static testMethod void  addPostOnTechClosedCase(){
       TestDataUtil.dataValueMapCSData();
       User usr = [Select Id , contactId,AccountId from User where isActive = true and Profile.Name='Pivotal - Community Manager' limit 1];
       system.assert(usr != null,'Issue in creating User');
       Case cObj1;
        System.runAs(usr){
           cObj1 = TestDataUtil.createCaseByPortalUser(usr);
           system.assert(cObj1.Id != null);
        }
       Entitlement ent = TestDataUtil.createEntitlement(cObj1.AccountId);
       System.assert(ent!=null);
       cObj1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
       cObj1.EntitlementId = ent.Id;
       cObj1.Status = 'Closed';
       update cObj1;
       System.runAs(usr){
           FeedItem ifeed = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           system.assert(ifeed.Id != null);
       }
    }  
    
    static testMethod void  addPostOnClosedCase(){
       TestDataUtil.dataValueMapCSData();
       User usr = [Select Id , ContactId , AccountId from User where isActive = true and Profile.Name='Pivotal - Community Manager' limit 1];
       system.assert(usr != null,'Issue in creating User');
       Case cObj1;
        System.runAs(usr){
           cObj1 = TestDataUtil.createCaseByPortalUser(usr);
           system.assert(cObj1.Id != null);
        }
       cObj1.Status = 'Closed';
       update cObj1;
       System.runAs(usr){
           FeedItem ifeed = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           system.assert(ifeed.Id != null);
       }
    }  
    
    
    static testMethod void  addPostonArticles(){
       TestDataUtil.dataValueMapCSData();
        Break_Fix__kav bf = new Break_Fix__kav();
        bf.Title = 'Test Articles';
        bf.UrlName = 'TestArticles';
        bf.Symptom__c = 'Test Articles';
        bf.Resolution__c = 'Test Articles';
        bf.Product__c  = 'Alpine Chorus for Pivotal Data Suite';
        insert bf;
        System.assert(bf.Id!=null);
        String arId = [SELECT KnowledgeArticleId FROM Break_Fix__kav WHERE Id = :bf.Id].KnowledgeArticleId;
        DatavalueMap__c  csDataList = DatavalueMap__c.getInstance('ArticleTypes');
        csDataList.Data_Value__c =arId.substring(0,3);
        update csDataList;
        System.assertEquals(arId.substring(0,3),csDataList.Data_Value__c , 'Not Match');
        KbManagement.PublishingService.publishArticle(arId, true);
        
        FeedItem ifeed = TestDataUtil.createFeedItem(arId,'AllUsers');
        system.assert(ifeed.Id != null);
        system.assertEquals(ifeed.ParentId ,arId);
        FeedComment cfeed = TestDataUtil.createfeedComment(ifeed.Id);
        system.assert(cfeed.Id != null);
    }
 }