src/objects/CategoryType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This list determines whether a Product Service Category is a Product or a service</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Category Type</label>
</CustomObject>

src/objects/CNS_Region__c.object
<CustomObject>
    <fields>
        <fullName>CNS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CNS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CNS_Rep_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER Data Sales</fullName>
                </value>
                <value>
                    <fullName>AMER Fed</fullName>
                </value>
                <value>
                    <fullName>AMER ISR</fullName>
                </value>
                <value>
                    <fullName>AMER Labs</fullName>
                </value>
                <value>
                    <fullName>AMER Other</fullName>
                </value>
                <value>
                    <fullName>AMER PDE</fullName>
                </value>
                <value>
                    <fullName>AMER Sub Renewals</fullName>
                </value>
                <value>
                    <fullName>AMER West</fullName>
                </value>
                <value>
                    <fullName>APJ Australia New Zealand</fullName>
                </value>
                <value>
                    <fullName>APJ Greater China</fullName>
                </value>
                <value>
                    <fullName>APJ India</fullName>
                </value>
                <value>
                    <fullName>APJ ISR</fullName>
                </value>
                <value>
                    <fullName>APJ Japan</fullName>
                </value>
                <value>
                    <fullName>APJ Korea</fullName>
                </value>
                <value>
                    <fullName>APJ Other</fullName>
                </value>
                <value>
                    <fullName>APJ South Asia</fullName>
                </value>
                <value>
                    <fullName>APJ Southeast Asia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Central North</fullName>
                </value>
                <value>
                    <fullName>Central South</fullName>
                </value>
                <value>
                    <fullName>Central West</fullName>
                </value>
                <value>
                    <fullName>EMEA Central</fullName>
                </value>
                <value>
                    <fullName>EMEA France &amp; S Europe</fullName>
                </value>
                <value>
                    <fullName>EMEA ISR</fullName>
                </value>
                <value>
                    <fullName>EMEA Labs</fullName>
                </value>
                <value>
                    <fullName>EMEA MEA</fullName>
                </value>
                <value>
                    <fullName>EMEA Other</fullName>
                </value>
                <value>
                    <fullName>EMEA UKI</fullName>
                </value>
                <value>
                    <fullName>Federal Civilian</fullName>
                </value>
                <value>
                    <fullName>Federal DoD/Intel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CNS Region</label>
    <nameField>
        <displayFormat>C-{00}</displayFormat>
        <label>CNS Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNS Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company_Code__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Spain</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency_Picklist__c</fullName>
        <label>Currency Picklist</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country_Uplift__c.object
<CustomObject>
    <description>Defines multiplier to List Price based on Sold To Country and  PSC
Formerly named County Uplift (API name Country_Uplift__c)</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Multiplier__c</fullName>
        <description>Multiplier applied for Services or Ed Services PSC products</description>
        <label>Service Multiplier</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Uplift_Multiplier__c</fullName>
        <label>Product Multiplier</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Country Multiplier</label>
    <nameField>
        <label>Country Multiplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Multiplier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

	public static Account createAccount(Boolean insertYN) {
		Account acc = new Account();
		acc.Name = 'Test Account';
		acc.Type = 'Customer';
		acc.BillingCountry = 'United States';
	    acc.BillingState = 'Washington';

		if(insertYN) {insert acc;}

		return acc;
	}

	public static Contact createContact(Id accID, Boolean insertYN) {
		
		Contact ctt = new Contact();
	    ctt.FirstName = 'Test';
	    ctt.LastName = 'Contact';
	    ctt.Email = 'email@mail.me';
	    ctt.MailingCountry = 'United States';
	    ctt.MailingCountryCode = 'US';
	    ctt.MailingState = 'Washington';
	    ctt.MailingStateCode = 'WA';
	    ctt.MailingPostalCode = '12345';
	    ctt.MailingStreet = '123 Main St.';
	    ctt.MailingCity = 'Seattle';
	    ctt.Phone = '404-444-4444';
	    ctt.AccountId = accID;

	    if(insertYN) {insert ctt;}

	    return ctt;
	}

	public static Opportunity createOpportunity(Id accID, Boolean insertYN) {
		Opportunity opp = new Opportunity();
		opp.Name = 'Test Opportunity';
		opp.AccountId = accID;
		opp.StageName = 'Technical Validation';
		opp.Forecast_Status__c = 'Pipeline';
		opp.Amount = 100;
		opp.CloseDate = System.today() + 30;

		if(insertYN) {insert opp;}

		return opp;
	}

	public static OpportunityLineItem createOpportunityLineItem(Id oppID, Id pbEntryID, Decimal price, Boolean insertYN) {
		OpportunityLineItem oppLine = new OpportunityLineItem();
		oppLine.OpportunityId = oppID;
		oppLine.PricebookEntryId = pbEntryID;
		oppLine.UnitPrice = price;
		oppLine.Software_Type__c = 'Subscription';
		oppLine.Months__c = 12;


		if(insertYN) {insert oppLine;}

		return oppLine;
	}

	public static void createCompanyCode(Boolean insertYN) {
		Company_Code__c cc = new Company_Code__c();
		cc.Code__c = 'US46';
		cc.Country__c = 'US';
		cc.City__c = 'Seattle';
		cc.Currency_Picklist__c = 'USD';

		if(insertYN) {insert cc;}
	}

	public static Product2 createProduct2(Boolean insertYN) {
		Product2 prod = new Product2();
		prod.Name = 'Test Product';
		prod.IsActive = true;
		prod.ProductCode = 'PCF';
		prod.Report_Category__c = 'PaaS';
		prod.ProductCode = 'SSS-0000';

		if(insertYN) {insert prod;}

		return prod;
	}

	public static Pricebook2 createPricebook2(Boolean insertYN) {
		Pricebook2 pbk = new Pricebook2();
		pbk.Name = 'Test Pricebook';
		pbk.IsActive = true;

		if(insertYN) {insert pbk;}

		return pbk;
	}

	public static PricebookEntry createPricebookEntry(Id prodID, Decimal price, Boolean insertYN) {
		PricebookEntry pbEntry = new PricebookEntry();
		pbEntry.Product2Id = prodID;
		pbEntry.UnitPrice = price;
		pbEntry.IsActive = true;
		pbEntry.Pricebook2Id = Test.getStandardPricebookId();

		if(insertYN) {insert pbEntry;}

		return pbEntry;
	}

	public static Task createTask(Id leadId, Boolean insertYN) {
		Task taskObj = new Task();
		taskObj.whoId = leadId;
		taskObj.Subject = 'Send Email to User';
		taskObj.Status = 'New';
		taskObj.Priority = 'Normal';
		taskObj.Type = 'Phone Call';
		
		if(insertYN) {insert taskObj;}

		return taskObj;
	}

	public static Profile createProfile(String profileName) {
		return [SELECT Id FROM Profile WHERE Name = :profileName];
	}

	public static User createUser(Id profileId, Boolean insertYN) {
		User u = new User();
		u.Alias = 'standt';
		u.Email='standarduser@testorg.com';
		u.EmailEncodingKey='UTF-8';
		u.LastName='Testing';
		u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = profileId;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.UserName='UnitTestUser' + Math.round(Math.random()*1000) + '@testorg.com';
		u.Theater__c = 'AMER';
		u.Region__c = 'Pacific NorthWest';

		if(insertYN) {insert u;}

		return u;
	}

	public static UserRole createUserRole(String userRoleName) {
		insertUserRole(userRoleName);
		return [SELECT Id, Name FROM UserRole WHERE Name = :userRoleName]; 
	}

	public static Lead createLead(Boolean insertYN) {
		Lead ld = new Lead();
		ld.Company = 'Fancy Company';
		ld.Email = 'Fancy@email.com';
		ld.FirstName = 'Lead';
		ld.LastName = 'Lady';

		if(insertYN) {insert ld;}

		return ld;
	}

	public static Country_Uplift__c createCountryUplift(String countryCode,
														Decimal productMultipler,
														Decimal serviceMultipler,
														Boolean insertYN) {
		Country_Uplift__c countryUplift = new Country_Uplift__c();
		countryUplift.name = 'Test + ' + countryCode;
		countryUplift.Country_Code__c = countryCode;
		countryUplift.Uplift_Multiplier__c = productMultipler;
		countryUplift.Service_Multiplier__c = serviceMultipler;
		if (insertYN) { insert countryUplift; }

		return countryUplift;
	}

	public static void createCategoryType(String name, String type) {
		CategoryType__c categoryType = new CategoryType__c();
		categoryType.Name = name;
		categoryType.Type__c = type;
		insert categoryType;
	}

	@future
	private static void insertUserRole(String userRoleName) {
		UserRole userRoleObj = new UserRole();
		userRoleObj.Name = userRoleName;
		insert userRoleObj;
	}

	@future
  	public static void assignUserRole(Id userId, Id roleId) {
	    User u = new User();
	    u.Id = userId;
	    u.UserRoleId = roleId;
	    update u;
	}

	public static CNS_Region__c createCNSRegion(Id userId, String Region) {
		CNS_Region__c cnsRegion = new CNS_Region__c();
		cnsRegion.Region__c = Region;
		cnsRegion.CNS_Rep__C = userId;

		insert cnsRegion;

		return cnsRegion;
	}


}