src/objects/Partnership__c.object
<CustomObject>
    <description>Used to to track the different partnership tracks that an Account may enter into.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account that the Partnership is for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnerships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>The specific Program that the Account is applying for.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnerships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Identifies the states of the partnership.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>No Potential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>Used to track the difference partnership tracks that an Account may enter into.</description>
    <label>Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/trac_Account_Test.cls
@isTest
private class trac_Account_Test {
	
	@isTest static void createPartnershipsAfterAccountInsertTest() {
		//create A Program
		Program__c program = new Program__c(Name = 'Test Program');
		insert program;

		//create an Account that references the program (this theorectically happens after the lead gets converted)
		Account acct = new Account(Name='Account Test', Type = 'Analyst', Program__c = program.Id);
		insert acct;

		List<Partnership__c> partnerships = [SELECT Id, Account__c, Program__c, Status__c FROM Partnership__c];

		System.assertEquals(partnerships.size(), 1);
		System.assertEquals(partnerships[0].Account__c, acct.Id);
		System.assertEquals(partnerships[0].Program__c, program.Id);
		System.assertEquals(partnerships[0].Status__c, 'Approved');

		acct = [SELECT Id, Program__c FROM Account WHERE Id =: acct.Id];

		System.assertEquals(acct.Program__c, null);
	}
	
	@isTest static void createPartnershipsAfterAccountUpateTest() {
		//create A Program
		Program__c program = new Program__c(Name = 'Test Program');
		insert program;
		Program__c program2 = new Program__c(Name='2nd Program Test');
		insert program2;

		//create an Account that references the program (this theorectically happens after the lead gets converted)
		Account acct = new Account(Name='Account Test', Type = 'Analyst', Program__c = program.Id);
		insert acct;

		List<Partnership__c> partnerships = [SELECT Id, Account__c, Program__c, Status__c, Name FROM Partnership__c];

		System.assertEquals(partnerships.size(), 1);
		System.assertEquals(partnerships[0].Account__c, acct.Id);
		System.assertEquals(partnerships[0].Program__c, program.Id);
		System.assertEquals(partnerships[0].Status__c, 'Approved');
		System.assertEquals(partnerships[0].Name, 'Account Test - Test Program');

		acct = [SELECT Id, Program__c FROM Account WHERE Id =: acct.Id];

		System.assertEquals(acct.Program__c, null);

		
		acct.Program__c = program2.Id;
		update acct;

		List<Partnership__c> partnerships2 = [SELECT Id, Account__c, Program__c, Status__c FROM Partnership__c];
		System.assertEquals(partnerships2.size(), 2);
		acct = [SELECT Id, Program__c FROM Account WHERE Id =: acct.Id];

		System.assertEquals(partnerships2[0].Account__c, acct.Id);
		System.assertEquals(partnerships2[1].Account__c, acct.Id);

		System.assertEquals(acct.Program__c, null);
	}
	
}