src/objects/Partnership__c.object
<CustomObject>
    <description>Used to to track the different partnership tracks that an Account may enter into.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account that the Partnership is for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnerships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>The specific Program that the Account is applying for.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnerships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>Used to track the difference partnership tracks that an Account may enter into.</description>
    <label>Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/trac_Partnership.cls
/* 
 * @description		Methods for the Parntership trigger.
 * @author			Merisha Shim, traction on demand
 * @date			02/25/2014
 *
 */ 

 /** THis method fires after partnerships have been created */
public with sharing class trac_Partnership {
	public static void updateAccountProgramWithNull(List<Partnership__c> newPartnerships) {
		
		Set<Id> acctListIds = new Set<Id>();

		for(Partnership__c p : newPartnerships) {
			acctListIds.add(p.Account__c);
		}
		List<Account> acctList = new List<Account>(); 
		List<Account> acctToUpdate = new List<Account>();
		
		if(!acctListIds.isEmpty()) {
			 acctList = [SELECT Id, Program__c FROM Account WHERE Id IN: acctListIds AND Program__c != null];
		}

		for(Account a : acctList) {
			a.Program__c = null;
			acctToUpdate.add(a);
		}

		if(!acctToUpdate.isEmpty()) {
			update acctToUpdate;
		}
	}
}