src/objects/Partnership__c.object
<CustomObject>
    <description>Used to to track the different partnership tracks that an Account may enter into.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account that the Partnership is for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnerships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to easily report on the Active Partnerships. Initially will look at the Status and Agreement Expiry.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>The specific Program that the Account is applying for.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnerships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Identifies the states of the partnership.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>No Potential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Identifies the Partner level.</description>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>Used to track the difference partnership tracks that an Account may enter into.</description>
    <label>Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/trac_Account.cls
/* 
 * @description		Methods for the Account trigger.
 * @author			Merisha Shim, traction on demand
 * @date			02/25/2014
 *
 */ 
public with sharing class trac_Account {
	
	/* Method that creates a partnership when an account is created. */
	public static void createAndUpdatePartnershipAfterAccountInsert(List<Account> newAccts) {
		List<Account> acctsList = new List<Account>();
		Set<Id> programIds = new Set<Id>();
		
		for(Account a : newAccts) {
			if(a.Program__c != null) {
				acctsList.add(a);
				programIds.add(a.Program__c);
			}
		}
		Map<Id, Program__c> programNames = new Map<Id, Program__c>();
		if(programIds.size() > 0) {
			programNames = new Map<Id, Program__c>([SELECT Id, Name FROM Program__c WHERE Id IN: programIds]);
		}
		//We need to get the contact Id of lead account that is related
		//List<Lead> leadLists = [SELECT Id, ConvertedContactId FROM Lead WHERE ConvertedAccountId IN : acctListIds];

		List<Partnership__c> partnershipsToInsert = new List<Partnership__c>();
		
		for(Account acct : acctsList) {
			Partnership__c partnership = new Partnership__c();
			partnership.Name = acct.Name + ' - ' + programNames.get(acct.Program__c).Name;
			partnership.Account__c = acct.Id;
			partnership.Program__c = acct.Program__c;
			partnership.Status__c = 'Approved';
			partnership.Active__c = true;
			partnership.Tier__c = 'Registered';
			partnershipsToInsert.add(partnership);
			
		}
		if(!partnershipsToInsert.isEmpty()) {
			insert partnershipsToInsert;
		}
		
		
	}

	
}